package kong

import (
	"fmt"

	"github.com/hashicorp/terraform/helper/schema"
	"github.com/kevholditch/gokong"
)

func resourceKongConsumerPluginConfig() *schema.Resource {
	return &schema.Resource{
		Create: resourceKongConsumerPluginConfigCreate,
		Read:   resourceKongConsumerPluginConfigRead,
		Delete: resourceKongConsumerPluginConfigDelete,
		Update: resourceKongConsumerPluginConfigUpdate,

		//Importer: &schema.ResourceImporter{
		//	State: schema.ImportStatePassthrough,
		//},

		Schema: map[string]*schema.Schema{
			"consumer_id": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"plugin_name": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"config_json": &schema.Schema{
				Type:     schema.TypeString,
				ForceNew: true,
				Optional: true,
				Default:  nil,
			},
		},
	}
}

func resourceKongConsumerPluginConfigCreate(d *schema.ResourceData, meta interface{}) error {

	consumerPluginConfig, err := createKongPluginConfig(d, meta)

	if err != nil {
		return fmt.Errorf("failed to create kong consumer plugin config, error: %v", err)
	}

	d.SetId(consumerPluginConfig.Id) //This is always unique generated by kong, regenerated on update

	return resourceKongConsumerPluginConfigRead(d, meta)
}

func resourceKongConsumerPluginConfigUpdate(d *schema.ResourceData, meta interface{}) error {
	d.Partial(false)
	err := resourceKongConsumerPluginConfigDelete(d, meta) //Config changed.  Delete the old config
	consumerPluginConfig, err := createKongPluginConfig(d, meta)

	if err != nil {
		return fmt.Errorf("error updating kong plugin: %s", err)
	}
	d.SetId(consumerPluginConfig.Id) //Reset Id to newly regenerated Id
	return resourceKongConsumerPluginConfigRead(d, meta)
}

func resourceKongConsumerPluginConfigRead(d *schema.ResourceData, meta interface{}) error {
	pluginName := readStringFromResource(d, "plugin_name")
	consumerID := readStringFromResource(d, "consumer_id")
	consumerPluginConfig, err := meta.(*gokong.KongAdminClient).Consumers().GetPluginConfig(consumerID, pluginName, d.Id())

	if err != nil {
		return fmt.Errorf("could not find kong consumer plugin config with id: %s error: %v", d.Id(), err)
	}

	if consumerPluginConfig == nil {
		d.SetId("")
	} else {
		d.Set("id", consumerPluginConfig.Id)
		d.Set("config_json", consumerPluginConfig.Body)
	}
	return nil
}

func resourceKongConsumerPluginConfigDelete(d *schema.ResourceData, meta interface{}) error {
	pluginName := readStringFromResource(d, "plugin_name")
	consumerID := readStringFromResource(d, "consumer_id")
	err := meta.(*gokong.KongAdminClient).Consumers().DeletePluginConfig(consumerID, pluginName, d.Id())

	if err != nil {
		return fmt.Errorf("could not delete kong consumer plugin config: %v", err)
	}

	return nil
}

func createKongPluginConfig(d *schema.ResourceData, meta interface{}) (*gokong.ConsumerPluginConfig, error) {
	pluginName := readStringFromResource(d, "plugin_name")
	pluginConfig := readStringFromResource(d, "config_json")
	consumerID := readStringFromResource(d, "consumer_id")
	plugin, err := meta.(*gokong.KongAdminClient).Consumers().CreatePluginConfig(consumerID, pluginName, pluginConfig)
	return plugin, err
}
